//--------------------ioctl----

#define SCULL_IOC_MAGIC 'l'

#define SCULL_IO_RESET _IO(SCULL_IOC_MAGIC, 0)

#define SCULL_IO_SET_QUANTUM _IOW(SCULL_IOC_MAGIC, 3, int)
#define SCULL_IO_SET_QSET _IOW(SCULL_IOC_MAGIC, 4, int)

#define SCULL_IO_TELL_QUANTUM _IO(SCULL_IOC_MAGIC, 5)
#define SCULL_IO_TELL_QSET _IO(SCULL_IOC_MAGIC, 6)

#define SCULL_IO_GET_QUANTUM _IOR(SCULL_IOC_MAGIC, 1, int)
#define SCULL_IO_GET_QSET _IOR(SCULL_IOC_MAGIC, 2, int)

#define SCULL_IO_QUERY_QUANTUM _IO(SCULL_IOC_MAGIC, 7)
#define SCULL_IO_QUERY_QSET _IO(SCULL_IOC_MAGIC, 8)

